### ISSUE TITLE
Integration version not compatible with Card version

### ISSUE THREAD

**Issue by steflrx** [ssenart/lovelace-gazpar-card#37]
Hello,
not understood why the following error message:
![image](https://github.com/user-attachments/assets/0b6faacc-7881-465c-9f77-86c4c2082a40)

from HACS console status is the following:
![image](https://github.com/user-attachments/assets/08d6f263-f567-4b2d-b405-653a5b1f441a)

Core 2024.10.1
Supervisor 2024.10.0
Operating System 13.1
Interface utilisateur 20241002.2

**Comment by ssenart** [comment]
Hello, the message corresponds to a bug inside the card version 1.3.9 working with the integration version 1.3.10.

It has been fixed in the card version 1.3.10.

It seems that your card version 1.3.10 is not executed despite it is installed. Could you restart your HA and ensure your browser file cache is cleared.

**Comment by steflrx** [comment]
Downgrade and upgrade solve the issue, thanks for your support
